//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rebel.WS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RebelRegister
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string planet { get; set; }
        public Nullable<System.DateTime> registerdate { get; set; }
    }
}
